### PR TITLE
Do not attempt to match 'escaped' brackets

### PR DESCRIPTION
**Pull request by FichteFoll**
Previously, BH would complain about incorrectly matched brackets in regular expressions for example, if they were escaped with backslashes. This fixed it.

See also https://github.com/SublimeText/AAAPackageDev/issues/61

Edit: It's great how easy this is!

### CODE REVIEW

**Comment by facelessuser** [comment]
There's also a string escape mode that you can swap to regex mode.  Look in the command palette and the settings file.

**Comment by facelessuser** [comment]
Please read here about escape modes: http://facelessuser.github.io/BracketHighlighter/usage/#toggle-string-bracket-escape-mode.

And here about changing the default setting: http://facelessuser.github.io/BracketHighlighter/customize/#bracket_string_escape_mode.

Let me think about this change.  I also deal with regex in actual strings that aren't handled raw, and in those cases, I need to be able to count an escape as `\\(` opposed to '\(`.  For this reason, I added the escape modes.  Normal strings may still need  escape modes, and if so, I don't want to merge this unless I have them playing nice together.

**Comment by FichteFoll** [comment]
For some reason, running the "Toggle String Bracket Escape Mode" command only displays text about the current mode in the status bar, but doesn't actually change behavior. I tested with the text in https://github.com/SublimeText/AAAPackageDev/issues/61 and the "Sublime Text Syntax Def (YAML)" syntax. Neither string nor regex mode seem to help at all. I don't think there is anything else I need to do?

**Comment by facelessuser** [comment]
Okay, I understand better.  The feature I mentioned works for sub-brackets in strings, but since yaml omits brackets for some strings, they aren't recognized by BH as quoted strings; therefore, they get they don't have the escape modes applied.

So I actually took time to install AAAPackageDev, and I have a couple more suggestions for this pull:

1. For changes that are very language specific, and really aren't desired globally, I would prefer that the excludes scopes be namespaced so that unexpected behavior doesn't get picked up my unsuspecting languages.  So I would prefer a format like this: `constant.character.escape.general.regexp`.

2. AAAPackageDev also has a problem with quoted regex strings as the way AAAPackageDev scopes quoted strings, they will not be recognized by BH.  This can be fixed by applying a exclude exception for those types of strings via `meta.value.yaml-tmlanguage`.  But since we want to uphold your `constant.characer.escape.general.regexp`, we would format it like this: `meta.value.yaml-tmlanguage -constant.character.escape.general.regexp`

```js
{
            "name": "round",
            "open": "(\\()",
            "close": "(\\))",
            "style": "round",
            "scope_exclude_exceptions": [
                "text.tex string.other.math",
                "punctuation.definition.string.begin.shell",
                "punctuation.definition.string.end.shell",
                "meta.value.yaml-tmlanguage -constant.character.escape.general.regexp"
            ],
            "scope_exclude": [
                "string",
                "comment",
                "punctuation.definition.case-pattern.shell",
                "constant.character.escape.general.regexp"
            ],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex"],
            "find_in_sub_search": "true",
            "ignore_string_escape": true,
            "enabled": true
        },
```

**Comment by FichteFoll** [comment]
Well, the reason why I used `constant.character.escape` is that in almost no situation would you ever want to bracket-match escaped brackets, and the `constant.character.escape` scope is exactly that. 

I fail to see how adding `"meta.value.yaml-tmlanguage -constant.character.escape.general.regexp"` to `scope_exclude_exceptions` does anything since that should not be excluded in the first place.

**Comment by facelessuser** [comment]
> I fail to see how adding "meta.value.yaml-tmlanguage -constant.character.escape.general.regexp" to scope_exclude_exceptions does anything since that should not be excluded in the first place.

Did you look at regex in quoted strings in your syntax?  I did.

**Comment by facelessuser** [comment]
I make no assumptions about escapes.  What about some embedded language in another languages string?  Escaped brackets are more of a regex thing, so why not limit the expectation to that?

**Comment by FichteFoll** [comment]
> Did you look at regex in quoted strings in your syntax? I did.

Can you give me an example please? I still can't see it.

> I make no assumptions about escapes. What about some embedded language in another languages string? Escaped brackets are more of a regex thing, so why not limit the expectation to that?

So, the current state is: change the exclude scope selector to `meta.value.yaml-tmlanguage constant.character.escape` to be more specific about the syntax used.

Alternatively, what can I do to make regex mode work in this syntax?

**Comment by facelessuser** [comment]
I'll reinstall AAAPackageDev again later and post some screencaps.  What I posted was what I tested with; though I only posted the round example.  Whether you address quoted regex is really up to you.  I was just letting you know what was broken and how to fix it.

I will evaluate the escaping and let you know my final verdict.  I just don't think always excluding escaping chars in ALL syntaxes will turn out as expected.  That is why i want it more specific.  There is an assumption that all syntax writers are going to follow what you expect.

**Comment by facelessuser** [comment]
> Can you give me an example please? I still can't see it.

Quoted regex has no bracket recognition.  This is due to how it is scoped.

screenshot 2015-07-05 16 26 51

With `"meta.value.yaml-tmlanguage -constant.character.escape"` applied in scope_exclude_exceptions (plus your previous changes).

screenshot 2015-07-05 16 30 12

You can fix it if you want, but since I don't use AAAPackageDev, I am okay if you don't want to.  I just thought I would be helpful since I noticed it.  I might add something like this to highlight in unquoted strings in normal YAML.

> So, the current state is: change the exclude scope selector to meta.value.yaml-tmlanguage constant.character.escape to be more specific about the syntax used.

No.  I was more referring to `constant.character.escape.general.regexp` instead of `constant.character.escape`.  Though something like `source.yaml-tmlanguage constant.character.escape` might be even better as it targets `source.yaml-tmlanguage`.

In normal strings, regex escape or string escape mode mode kicks in for sub-brackets.  What you are adding is specifically needed because your syntax does not have its strings get recognized as quoted strings for the builtin feature to kick in. This is partly because YAML allows non-quoted strings, and partly because how AAAPackageDev scopes quoted strings in the syntax file.  So let's keep it scoped to just what we are trying to fix for now until I can evaluate things globally.  It better to start conservative and fix the problem we are seeing, than to be liberal and cause more problems we didn't expect.

Using `constant.character.escape` globally might be fine and I understand the logic that we never want to include escaped brackets, and maybe I will go that route in the future, but I need to time to evaluate a change that will globally affect things.  How will this play with string/regex other strings?  Do I need to kill off regex mode in Python raw strings if `constant.character.escape` solves this issue?  Would people want to use string mode escape instead of regex mode escape in Python raw strings for some reason?  I don't know yet, but I need time.

### Conclusion

- Use `source.yaml-tmlanguage constant.character.escape` for `scope_exclude` to solve the specific issue we are seeing.

- Optionally add `meta.value.yaml-tmlanguage -constant.character.escape` to `scope_exclude_exceptions` to fix your quoted regex problem.

If am open to other suggestions as well.  If you see some flaws in my logic, feel free to point them out.

**Comment by FichteFoll** [comment]
> Quoted regex has no bracket recognition. This is due to how it is scoped.

Ah, you mean the real brackets. I was a bit confused about your usage of "brackets" and "sub-brackets" earlier, which is why I didn't think of this being the real brackets. Yes, I am aware of the issue because I dicided to mark brackets as strings for different highlighting purposes. I do not think it's a problem if this is not highlighted because the syntax highlighting makes it pretty obvious where the bounaries are. I suppose it's better for consistency.

**Comment by facelessuser** [comment]
> Ah, you mean the real brackets. I was a bit confused about your usage of "brackets" and "sub-brackets" earlier, which is why I didn't think of this being the real brackets.

Sorry if I wasn't more clear.  Just thought if you were going through the effort to fix part of it, might as well fix all of it, but that is up to you.  I'm only picky if it affects something I use; just thought I'd point it out.

**Comment by FichteFoll** [comment]
Updated.

I would have split the other lists into multiple lines, but I wanted to keep the changes at a minimum.

**Pull request merged**
