### PR TITLE
Retina Icons

### PR DESCRIPTION
**Pull request by vemec**
Hi, I designed a first version of all the icons for retina displays.
I would really appreciate any comments to improve them.
Regarding the typography, I used Source code Pro.
Thanks!

### CODE REVIEW

**Comment by MilllerTime** [comment]
I'm on Windows 10 and am also experiencing tiny icons in the gutter, for this and other plugins like gitgutter. I guess it's beyond the control of package authors, which is a shame. Windows 10 has been notoriously awful at getting high-DPI scaling right, though. Looking forward to the day this works as expected, whether at the OS level or Sublime itself.

**Comment by r-stein** [comment]
@MilllerTime For GitGutter you can change [GitGutter theme](https://github.com/jisaacks/GitGutter/blob/1.5.1/GitGutter.sublime-settings#L112) to `Default HiDPI.gitgutter-theme` to use a different image set for the gutter

https://github.com/jisaacks/GitGutter/issues/199#issuecomment-284456805

**Comment by MilllerTime** [comment]
@r-stein Fantastic!! 🎉 This is a great workaround for GitGutter, thanks for the pointer!

It'd be nice if something similar could be achieved with BracketHighlighter, but either way this is a nice package as well 🙂

**Comment by facelessuser** [comment]
Is this still an issue?  GitGutter has a HiDPI theme, but if you look at them, they are just 32x32 images.  BH is already provides 32x32 images.  Images used to be super tiny, but on recent Sublime beta builds, they seem scaled more proper.

**Comment by facelessuser** [comment]
FYI.  Historically, no matter what size gutter icons where, Sublime scaled them down to 16x16 regardless of DPI.  I just created 32x32 icons and called it a day.  I figured that one day sublime would actually use the full resolution.  Recent builds (I'm on 3131) seem to no longer scale down the 32x32 icons to super tiny 16x16 on my 4k monitor.  If you are seeing something different or can provide more info as to more I can do, please let me know.

**Comment by MilllerTime** [comment]
Hey @facelessuser, I'm on build 3126, which is the latest stable. I'll give the beta build a shot and see if that improves things. I'm using a 4K monitor as well.

The BH icons are nearly the same size as GG, but they are not nearly as large as what is shown in the README. I believe the GG icons are smaller by design, as they are less detailed. With BH, I currently have trouble distinguishing parens from curly brackets (the image below is scaled up 250%).

capture

Still, the other features are awesome! Thanks for all the effort!

**Comment by facelessuser** [comment]
They might be a little smaller as I recall I do not take up the entire height and width of the 32x32 image.  This stems from the fact that old Sublime builds I believe clipped the image some (maybe I am remembering incorrect).  But also, as you shrunk line size the gutter size remained the same and would overlap other lines.  This is also why I provide a small variant that uses even less of the 32x32 image for really small lines (wouldn't really see this on a 4K monitor though).

Anyways, I'll be honest, I am not super excited about redoing all the icons, especially if we are talking about a very minimal difference in size. But I do understand that people may feel that new icons might help with distinguishing them.  I color code mine, and don't have a big issue with their shape in recent builds, but not all eyes are created equal.

Most likely, if I where to redo the icons, I would do what I did with original retina support (which is what got us to 32x32 size instead of 16x16) and ask the community to help out with providing new icons.

**Comment by MilllerTime** [comment]
> They might be a little smaller as I recall I do not take up the entire height and width of the 32x32 image.

That makes sense.

> I am not super excited about redoing all the icons

Haha, I don't blame you! Good news, though: I gave the beta build a try and everything is much better! Not only are gutter icons scaled properly, but now other aspects of the native UI aren't blurry at 4K like they are in the stable build. I see in build 3127 they "Refreshed UI theme, including full high DPI support". I imagine that will land in stable soon, but regardless it resolves this issue 🎉

**Comment by facelessuser** [comment]
@MilllerTime, Glad to hear.  It seemed good to me, but I wanted to make sure :slightly_smiling_face: .

**Comment by danilobytes** [comment]
After the latest update I got non-retina icons. They used to work nice.

Here's my support info:

```
- Sublime Text 3126
- Platform: osx
- Arch: x64
- GitGutter 1.7.1
- Install via PC: True
- git version 2.13.0
- mdpopups 1.13.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8
```

**Comment by facelessuser** [comment]
As mentioned earlier, you're going to have to get on a dev build (which requires a license) to get Sublime to scale them. Also, why are you posting GitGutter support info?  This is BracketHighlighter.

**Comment by danilobytes** [comment]
Wow, sorry mate. Messed up the comments... 😅

**Comment by facelessuser** [comment]
No problem 🙂 .

**Pull request merged**
