### PR TITLE
add support for @ attributes

### PR DESCRIPTION
**Pull request by ctf0**
fix for https://github.com/facelessuser/BracketHighlighter/issues/368

### CODE REVIEW

**Comment by facelessuser** [comment]
I think this should be placed under a new vue profile.

**Comment by ctf0** [comment]
not necessarily because u can write vue syntax in html,blade,vue components also the same linters that run on html can run on vue, also the @ is used in blade to force blade to ignore the `{{ }}`

but for vue component it self i will open an issue for it because there is something strange with its tag hl which is out of this pr scope.

**Comment by facelessuser** [comment]
Linters cab be written however they want, but vue files are opens in view syntax right?  I mean yeah, you could open a vue file in plain html syntax, but that isn't even really supported in html syntax highlighter, right?  I don't want to muddy the html tag rule unless there is a really good reason to.

**Comment by ctf0** [comment]
i can write vue syntax in blade as well as html, u r correct that not most of vue syntax will be properly highlighted in html but vue syntax is picked up only by files with `.vue` which mostly is only made for the vue components files

**Comment by facelessuser** [comment]
Why not create a blade/view profile?  People open lots of template type languages in straight html, but I don't think it is a good idea to modify the HTML regex to support **all** not default HTML derivatives.  There is nothing stopping you from opening a vue file with an `html` extension and from the quick panel selecting the vue syntax.  If I throw in vue, why not mix in cold fusion and other various implementations?  The rule will get really hard to maintain.

**Comment by ctf0** [comment]
in that case , we should remove blade,angular from the html scope and add them to its own settings.

**Comment by facelessuser** [comment]
I know nothing about angular and very little about blade, but PHP doesn't particularly change the HTML format, it can break up the format which can cause trouble, but I know of no way to create a regex that can detect all the different ways PHP can break HTML syntax as it can literally be inserted anywhere, there is nothing regular about it which is why regular expression I don't think will probably detect tags broken up with PHP.  The same could be said for Jinja2 or other template languages.  But the `@` support is predictable enough that a profile could be created to detect it as it is placed right before an HTML attribute.

I want make sure I am clear, detecting `@` is doable.  Detecting this `<tag <php? /*mucking up a tag with all sorts of nonsense*/ ?>></tag>` is very different.  BH has a difficult time with PHP in these scenarios and always will.

**Comment by ctf0** [comment]
am lost, so u want to make a new option just for the `@` ? if so then its better to have a setting for all the un-offecial supported html attrs `: , :: , _ , @`

**Comment by facelessuser** [comment]
I'm just saying we don't do anything special for PHP.  We have a separate non-tag related rule for PHP `<?php ?>` or even php keywords `if endif` etc.  Millage varies for those, but they are there.

I'm also saying, how do you create a rule that covers all these?

```php
<<?php "t" ?>ag></tag>
<t<?php "a" ?>g></tag>
<ta<?php "g" ?>></tag>
```

I'm simply trying to illustrate the difference between "PHP" support as a whole vs the problem you are seeing in vue, and I only brought it up to answer your question about  PHP, blade, vue, etc.  PHP is not really related to this discussion.  Maybe blade and angular is.  You are probably a bigger expert on this than I.

As for vue, I don't know what vue supports.  If it supports `:, ::, _, @`, then include them all.  Include anything that can be specifically and fully covered by regex.  It doesn't just have to come before the attribute, but it needs to be predictable.

Should blade, vue, and other template variants be included together?  I don't know, is the syntax the same for all of them?  Can they coexist with each other without getting difficult to maintain?  What would we need to support?  I am open to discussion.  Clearly I am not an expert on all the template languages, and understanding the situation better might help me make a better informed answer.

**Comment by ctf0** [comment]
okay i understand the issue about php, clearly solving this with regex will be kinda messy but regarding the attributes i have an idea, what if we made a separate setting just for those attributes like
```js
"cstm-attrs":
{
    syntax: ['html'] // where u want those attrs to be supported,
    attrs: ['@',':+','_'] // here u put ur custom attrs, this setting support both string and regex
},
```
so now we can have the html main setting cleaned like below , and any other language that derive from html will have their tags supported automatically because in essence they are the same as html except some small changes

```js
"tag_mode": {
        "xhtml": ["XML"],
        "html": [
            "HTML",
            "HTML 5",
            "PHP",
            "HTML (Jinja Templates)",
            "HTML (Rails)",
            "HTML (Twig)",
            "HTML (Django)",
            "Java Server Pages (JSP)"
        ],
        "cfml": ["HTML+CFML", "ColdFusion", "ColdFusionCFC"]
    },
```

so what u think ?

**Comment by facelessuser** [comment]
Let me think about this.

I had thought with the current settings users could allow what they wanted.  I believe that statement to be true even now, but you are requesting this additional flexibility which I am not yet sold on.

This is kind of limited in the regard that I can create a special list of attributes and assign them to particular syntaxes, but if I want to add one attribute to one kind of syntax, and one to another, this will not support that:

```js
"cstm-attrs":
{
    syntax: ['html','blade.php','vue','ng.html'] // where u want those attrs to be supported,
    attrs: ['@',':+','_'] // here u put ur custom attrs, this setting support both string and regex, ex. ':+'
},
```

**Comment by ctf0** [comment]
we can reverse it
```js
"cstm-attrs":
{
    "html":['@',':+','_']
    "blade":['@',':+','_']
    // etc
},
```

**Comment by facelessuser** [comment]
I've been thinking about this, and I still don't really see an advantage of adding another special attribute setting.  We already have an attribute setting, and that setting is used in things like attribute selection as well.  I understand you want to append additional attributes to the base html setting.  I would argue that you could just change the attribute setting for HTML in your personal setting to accommodate this if it is important to have as part of your personal settings.  Essentially, I am sticking with my original statement in #310.

The reason I suggested this be moved to a template profile or a vue profile is that this is not standard HTML syntax, so I suggested we create a non-standard profile for vue or possibly other templates that share similar syntax; I think this is a reasonable request.  With the current framework, we can create a non-standard profile by default.  If people want to make a non-standard profile their default for all HTML, they can do that in their User settings by changing the syntax associated with the given profile in `bh_tag.sublime-settings`.  They could even just copy the regex for attributes to their default HTML attribute regex if they desire.  This would be a User override choice.  The reason why I pushed all the settings to `bh_tag.sublime-settings` is 1) to make it easy for people to do pull request and 2) I figured the default will not always make everyone happy so they can override it in their User settings.  I am willing to put sane defaults in the settings, but users have the opportunity to deviate from the defaults if it suits their needs.  Users even have the option of adding whole new profiles in their user settings as well.

I am willing to accept `vue` syntax being added to the angle bracket rules, I willing to add a vue, blade, or whatever other template profile as necessary for blade and vue syntax etc.  If users want to copy the regex for non-standard vue and blade attributes to their default HTML attribute they can in their User settings.  If they want to map all HTML to use the template attributes in their User settings, that is good too.  This is why we have the settings file and settings file overrides.

**Comment by ctf0** [comment]
i second the option of having a separate profile for each template instead of having them all in html so the html stays true to its own specs,
but am kinda uncertain of why we have to add the template names in the html setting in both `bh_tag & bh_core` ???

**Comment by facelessuser** [comment]
Because we add vue to the angle rule which includes the tag bh_plugin to handle the more complex tag search logic.  Tag bh_plugin settings are kept to their own settings file to make a clear distinction that they are not core features.  Everything in bh_tag.sublime-settings is used in tags bh_plugin.  The only exception is that the attributes bh_plugin also reads in the attributes setting.

In short, the core angle rule would search vue syntax and pass that info to the tag bh_plugin. The tag bh_plugin identifies XML, html, cfml tags according to its settings.

**Comment by ctf0** [comment]
okay but maybe instead of the user having to add the rule in both places, maybe we can use the prev mentioned idea to make it easier, then the plugin will internally does the routing or piping from one setting to another :tada: partyyyyyyy

**Comment by facelessuser** [comment]
I guess I don't understand. We have to specify what syntax triggers a tag search, then we have to sort the syntax to apply the correct tag logic.  The previously suggested attributes setting doesn't really change that, it just presents the data in a different way.  Or maybe you are referring to something else?

**Comment by ctf0** [comment]
yes it does the same thing except it follows a pattern which many users are accustomed to, same like using ur smart phone to contact someone "the same pattern in any device , right ?", 

currently it requires extra steps to do something very simple which is not easily accessible in the doc

**Comment by facelessuser** [comment]
> which is not easily accessible in the doc

I'll give you that.  The documentation could probably be better, but hey it's a free plugin and there is some documentation, so I guess it isn't that bad 😉 .

> but currently it requires extra steps

What extra step?  Defining the syntax?  You have to do that in both. Defining the attribute?  You have to do that in both.  Attach it to the type of html document?  You have to do that to both.

The reason why it implemented in its current form is because it is flexible (maybe not pretty, but flexible).  And it is done is such a way the code can easily use the settings. Any aspect of the attribute that needs to be changed can be changed.  Does your use case allow unquoted attributes? Does it allow special characters within the attribute name? Does it allow special prefixes? You can change all of that. What you are asking for is very specific to your current interest, which is understandable, but when I exposed these settings my interest was a bit more broad: "how can I provide settings where anything the user wants to change can be changed so I don't have to do any extra work in the future".  The idea was to create less work for myself by exposing all the knobs so I could just say "you want it, modify it here".  I feel like a simple attribute regex setting was more than sufficient to fulfill that need.  Yeah you have to setup a profile, but it works well in the code like that:

What is current syntax?  PHP
What profile does PHP belong to? HTML
What does the attribute look like for HTML? some pattern

I just can't justify time implementing more code to essentially do what is already possible.  This isn't something that people are going to be frequently doing.  They deal with it maybe once or twice and then they set it and forget it.  When I am evaluating whether a feature is worth my time on the weekend, an alternative way to specify attributes that can already be specified just doesn't quite make the cut.

**Comment by ctf0** [comment]
okay, so the solution i believe for all that is simply refactoring the docs

**Comment by facelessuser** [comment]
Yeah, I try to explain things in the docs, but it doesn't always come out clear.  It is possible some better explanation in the documentation will clear up the confusion.

**Comment by ctf0** [comment]
and some simplifying would help big aswell, maybe try from a 6 years old pov instead of a dev one

**Comment by facelessuser** [comment]
Everyone always thinks they've made their docs clear at first; it's always after the fact that it behind obvious it is not.  I do accept pull requests on documents.  I'm not sure when I'll get to refactoring this particular area of the docs, but if no one gets to it before me, I'll take care of it... Assuming I don't just rephrase it in an exalt confusing manner :wink:.

**Comment by facelessuser** [comment]
No progress for a month.  Closing.

**Comment by BB-000** [comment]
I am still unclear how to add support for vue @click="example()" attributes

I can't find 'bh_tag.sublime-settings' ?

**Comment by Narretz** [comment]
Here's a gist with the changes that work for me for both Vue and plain html:

https://gist.github.com/Narretz/d496b92f850306d7c2eeb325bb9aa188

It's a bit disappointing that this was never merged

**Pull request closed without merging**
