### PR TITLE
Update HTML start tag regular expression

### PR DESCRIPTION
**Pull request by chigur**
Polymer has a custom attribute equality operator '$=' which breaks tag matching. Simply tweaking the HTML start tag regular expression does the trick.

### CODE REVIEW

**Comment by facelessuser** [comment]
I'm not sure how I feel about modifying the default HTML tag to accept invalid HTML.  I kind of feel this should be a separate regex.

Do you use a separate syntax highlighter for polymer?

**Comment by chigur** [comment]
I use the default HTML syntax highlighter that ships with Sublime Text 3 and given how close the syntax of Polymer's HTML is to the vanilla HTML a new syntax highlighter can hardly be justified. I do agree that it is kind of a bad idea to modify the default regular expression, but I couldn't think of a better way to do it. Also, most Polymer users will expect BracketHighlighter to work out of the box.

**Comment by facelessuser** [comment]
I will think about it.  I'm not too concerned with what Polymer users expect; I don't want to pollute normal tag detection if I can help it.  I imagine the $= will break current HTML syntax highlighting to some degree.  Do polymer files use a different file extension than HTML?

**Comment by chigur** [comment]
>I will think about it. I'm not too concerned with what Polymer users expect; I don't want to pollute normal tag detection if I can help it.

Makes sense, no problem.

>Do polymer files use a different file extension than HTML?

No. They are almost plain HTML with the exception that you can [annotate markup](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#property-binding) with bindings. There is no special syntax for control structures like if-else statements of for in Polymer, they are handled via [template tags and attributes](https://github.com/Polymer/polymer/blob/e13b28143d0a4623b0818b3c3bea78485aa87693/test/smoke/distribute-dom-repeat.html#L32).

**Comment by facelessuser** [comment]
Thanks for the info.  I guess that means there will be no easy way to distinguish polymer from HTML.  Hmm...this might be the only reasonable way then...

**Comment by facelessuser** [comment]
The plan moving forward is to expose the tag regex so people can modify it in their settings file.  This way I can ship with something more standard, but allow people to modify it for less standard HTML moving forward.  I've started the work here https://github.com/facelessuser/BracketHighlighter/commit/a7cc1e2a17bc854bd4a86af4233c38e3aa69e3c7.

**Comment by facelessuser** [comment]
The next version of BH will allow you to change a tag_mode's settings locally to support non-standard HTML like polymer.  You can even add new tag_modes if desired to keep your non-standard HTML tag modes separate. https://github.com/facelessuser/BracketHighlighter/blob/master/bh_tag.sublime-settings.  

This will allow you to have your desired functionality moving forward by updating your user bh_tag.sublime-settings file.  I've done it this way so anyone can come in add support for whatever HTML variant they need, and if I choose to not accept the pull request, they will still be able to just modify their user setting and have what they want regardless.


Though I still need to do documentation, I will consider this issue closed.  I will hopefully have a new release within the week.

**Pull request closed without merging**
