### PR TITLE
Add brackets for Lua

### PR DESCRIPTION
**Pull request by FichteFoll**
^title

Technically, `repeat` and `until` are their own kind of brackets, but it doesn't seem like you can have two different groups in a single pattern (i.e. capturing group 1 in open matches 1 in close, 2 ... 2 etc.) and you didn't add different brackets for php either, so I figured this would *just do*.

Edit: I just saw that you used `plugin_library` and `bh_modules.phpkeywords`. Should I do this as a plugin too?

### CODE REVIEW

**Comment by facelessuser** [comment]
> Edit: I just saw that you used plugin_library and bh_modules.phpkeywords. Should I do this as a plugin too?

Probably.  I am not entirely sure what you mean about `repeat` and `until` (I don't code in Lua).  But looking at the rule, it looks like you have two types of closings which I assume means that some openings pair with one and some pair with the other.  If this is the case, then you probably need a `compare` event where you can ensure the right opening and paired with the right closing (also ensuring case sensitivity can be done there as well).

**Comment by FichteFoll** [comment]
Alright, docs were really helpful with that.  :+1: Works like a charm now.

---

I'll apologize for my following tidbits in advance, but they are really well-intentioned.

Followup question: Is there anything for handling the middle parts of an `if .. elseif .. else .. end` block? Referring to elseif and else here. You certainly don't seem to handle them for php or ruby, which are one of the few cases where this would be an issue.

Followup bug: When specifying a plugin_library that does not exist, the following is printed to the console: `BracketHighlighter: 'tuple' object has no attribute 'splitlines'`. It's kind of ... intransparent.

Followup suggestion: extend `BracketRegion` class to have a `text` attribute, since `bfr[first.begin:first.end]` is a *really common* expression in plugins. Downside is that you kind of hard-code something view-specific.
Or better rename it to `Bracket` and include the bfr view context to it because when will you ever use this on a different object than `bfr`?

Followup minor things concerning the docs:

- Your description of `find_in_sub_search` is borked: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-brackets-rules
- I also think you should mention the case-insensitivity earlier than [here](http://facelessuser.github.io/BracketHighlighter/customize/#validate).
- The code is also outdated.

- Suggestion: Allow multiple plugins to be specified, and rename `erlangcase.py` to just `lowercase.py`. That way I could utilize the lowercase check for Lua too without awkwardly including it via `from .erlangcase import validate` (not gonna do that actually).
- Alternative suggestion: param for case-sensitive matching of brackets.

---

I can open separate issues if you want me to.

**Comment by facelessuser** [comment]
> Followup question: Is there anything for handling the middle parts of an if .. elseif .. else .. end block? Referring to elseif and else here. You certainly don't seem to handle them for php or ruby, which are one of the few cases where this would be an issue.

No, BH matches brackets or end caps: start and end.  We apply it to `if` blocks because it works well enough, but obviously `if` blocks aren't simple brackets.

> Followup bug: When specifying a plugin_library that does not exist, the following is printed to the console: BracketHighlighter: 'tuple' object has no attribute 'splitlines'. It's kind of ... intransparent.

Fair enough.  I always put in the correct plugin, so I never really knew what it spit out.

> Followup suggestion: extend BracketRegion class to have a text attribute, since bfr[first.begin:first.end] is a really common expression in plugins. Downside is that you kind of hard-code something view-specific.
Or better rename it to Bracket and include the bfr view context to it because when will you ever use this on a different object than bfr?

I agree it could be improved.  It isn't something that people dive into too much, so the motivation to enrich the experience was low, but I can make a note an improve it when I get some time.

> Your description of find_in_sub_search is borked:

Probably not the only thing that is borked.

> I think you should mention the case-insensitivity earlier than here.

Yeah, probably.

> The "validate" code is outdated, but still valid.

Yeah, maintaining docs is my weakness.

> Suggestion: Allow multiple plugins to be specified, and rename erlangcase.py to just lowercase.py. That way I could utilize the lowercase check for Lua too without awkwardly including it via from .erlangcase import validate (not gonna do that actually).

You can actually import other modules into other modules either using `import_from` or `import_module`  I guess you could chain the calls together.  I wonder if I documented that...I'll have to look that up.  

```python
from BracketHighlighter.bh_plugin import ImportModule as ImpMod
BracketRemove = ImpMod.import_from("bh_modules.bracketremove", "BracketRemove")
```

I should probably create a `lowercase.py` and import it into others as an example.  I guess I would prefer that than looping multiple modules in the API.

> Alternative suggestion: param for case-sensitive matching of brackets.

I think just importing the common module and chaining them should be enough.

> I can open separate issues if you want me to.

I say read through my responses, and anything without a suitable answer, just open a new issue.  Separate issues is easier for me to track.

Thanks for all the input and the request!

**Comment by FichteFoll** [comment]
Answers are suitable. Just a few clarifications.

re `BracketRegion` section: I edited that, so you might want to check out the changes too.

re importing: The name `erlangcase.py` just threw me off, kind of. It screams "I am context-sensitive" to me, so importing it just for the case-sensitivity seemed too insecure to me. I'm fine with importing from something named `lowercase.py`.
I don't really see an advantage for using `bh_plugin.ImportModule` over just relative importing what I need.

**Comment by facelessuser** [comment]
> re importing: The name erlangcase.py just threw me off, kind of. It screams "I am context-sensitive" to me, so importing it just for the case-sensitivity seemed too insecure to me. I'm fine with importing from something named lowercase.py.

Yeah, renaming is what I need to do.  I agree.

> I don't really see an advantage for using bh_plugin.ImportModule over just relative importing what I need.

bh_modules are not in the system path, that's why it exists.  You are free to just `import` if you want, but you won't get what you need.  I won't go into all the details, but currently it is a necessity, but basically, I don't won't Sublime auto loading them, so I load and unload as needed.

**Comment by facelessuser** [comment]
> Edit: I suppose the copyright notice I copy-pasted is ... wrong. You obviously can't have copyright on that starting 2013 if it was only added in 2015. I'm not a fan of per-file license/copyright plates anyway, if they are identical to the project's.

Yeah, I'll clean that up some time.  It's more project wide just copied in every file.  But then that requires maintenance.  Really it should just be more generic header stating license and and author, and the project license should detail dates etc.  Don't worry about.  I'll fix it.

**Pull request merged**
